apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-app
  labels:
    app: fitness-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness-app
  template:
    metadata:
      labels:
        app: fitness-app
    spec:
      containers:
      - name: fitness-app-container
        image: fitness-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        workingDir: /app/ACEestFitness
        command: ["python"]
        args: ["app.py"]
